### ISSUE TITLE
`cargo audit` finding for `atty` v0.2.14

### ISSUE THREAD

**Issue by martinfrances107** [phylum-dev/birdcage#42]
When I run ```cargo audit``` I see this issue.

Crate:     atty
Version:   0.2.14
Warning:   unsound
Title:     Potential unaligned read
Date:      2021-07-04
ID:        RUSTSEC-2021-0145
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0145
Dependency tree:
atty 0.2.14
└── clap 3.2.25
    └── birdcage 0.3.1

warning: 1 allowed warning found

**Comment by maxrake** [comment]
Thank you for the issue submission!

The [linked advisory](https://rustsec.org/advisories/RUSTSEC-2021-0145) indicates that this affects Windows, which Birdcage does not support. Still, the `atty` dependency only gets pulled in due to a `clap` dev-dependency pinned to the 3.x version.

`clap` is only used for the `examples/sandbox.rs` and so it does not affect the library code. Even still, we will work to get that dependency updated to a 4.x version, which does not require `atty`.

**Comment by maxrake** [comment]
Update: bumping the `clap` version to v4 has a side-effect:

```
error: package `clap_builder v4.4.2` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.63.0
```

Dropping support for `rustc` versions between 1.63.0 and 1.70.0 is less desirable than silencing this `cargo audit` warning. Plus, since the finding does not affect systems that Birdcage supports (e.g., Linux and macOS), it is deemed to be very low priority. For those reasons, this issue will be closed as "won't fix."

An externally submitted PR removing the use of `clap` entirely would be considered...
